### PR TITLE
Release/upstream 0.10.4

### PR DESCRIPTION
**Pull request by Danieloni1**

### CODE REVIEW

**Comment by Danieloni1** [comment]
@PiotrKozimor 
Please note conflicting changes:
1. stream_presence.go
2. sytest-whitelist

**Comment by PiotrKozimor** [comment]
I think you resolved conflicts right, but we still need unit tests to pass

**Comment by Danieloni1** [comment]
> I think you resolved conflicts right, but we still need unit tests to pass

@PiotrKozimor 
Ok so it seems like there was a change in the naming of certain DB tables. For some reason the migrations aren't executed on our tests locally and here. Do you know how to solve this?

This is the refactoring PR from upstream?
https://github.com/matrix-org/dendrite/pull/2806

**Comment by Danieloni1** [comment]
> UpNoGuests

Sorry for the back-and-forth but I don't understand how it is outdated if I merged latest remote tag into main 🤔
And in general- how do I pull the right changes to include this migration?

**Comment by PiotrKozimor** [comment]
This is our own migration, not present in upstream, so there was actually no way to avoid this issue other than manually inspecting upstream commits. Thankfully tests detected issue here 👌

**Review by PiotrKozimor — APPROVED** [review]

**Pull request merged**
