### PR TITLE
Feature/login with email

### PR DESCRIPTION
**Pull request by PiotrKozimor**
Put first step to resolve [issue](https://github.com/matrix-org/dendrite/issues/1858). Sytest test case will however not pass, because it expects HS to send confirmation email by itself.

### CODE REVIEW

**Comment by PiotrKozimor** [comment]
@danpe please review, we are now making requests to ID server by HTTPS.

**Comment by danpe** [comment]
@PiotrKozimor Is this supported in `Synapse` currently so `clients` & `admin_as` are compatible with both `Synapse` and this `Dendrite` fork?

**Review by danpe — APPROVED** [review]

**Comment by PiotrKozimor** [comment]
> @PiotrKozimor Is this supported in `Synapse` currently so `clients` & `admin_as` are compatible with both `Synapse` and this `Dendrite` fork?

Yes, there will be compatibility. [This function](https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/auth.py#L80) handles legacy fields in synapse.

**Comment by danpe** [comment]
Perfect.






On Mon, May 24, 2021 at 3:52 PM PiotrKozimor ***@***.***>  wrote:


@PiotrKozimor  Is this supported in Synapse  currently so clients  & admin_as 
are compatible with both Synapse  and this Dendrite  fork?

Yes, there will be compatibility. This function  handles legacy fields in
synapse.

**Pull request merged**
